{{- if .Values.nodeClient.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-client-pod
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: node-client-pod
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: node-client-pod
    spec:
      serviceAccountName: default
      serviceAccount: default
      {{- with .Values.nodeClient.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      hostPID: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: node-client-pod
          image: "{{ .Values.nodeClient.image.repository }}:{{ .Values.nodeClient.image.tag }}"
          imagePullPolicy: Always
          securityContext:
            privileged: true
      terminationGracePeriodSeconds: 1200
      restartPolicy: Always
{{- end }}
